name: test-actions

on:
  push:
    branches: main

  jobs:
    build:
      runs-on: ubutu-latest
      steps:
          -uses: actions/checkout@v1
          -name: run a sample
           run: echo Hello World
      
