name: test-actions

on:
  push:
    branches: main
    
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Message
      run: echo "Hello World"
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: build-artifact
        path: ${(github-artifacts)}
      
