name: test-actions

on:
  push:
    branches: main
    
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Message
      run: echo "Hello World" > build/test.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: ${( github.artifacts )}
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: ${( github.workplace )}
  
      
